In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("Advertising.csv")
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
df = df.drop("Unnamed: 0", axis=1)
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop("sales", axis=1).to_numpy()
X[:5]

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4]])

In [5]:
y = df["sales"].to_numpy()
y[:5]

array([22.1, 10.4,  9.3, 18.5, 12.9])

In [6]:
w_true = np.linalg.inv(X.T @ X) @ X.T @ y
w_true

array([0.05379188, 0.22222731, 0.01681639])

In [7]:
model = LinearRegression().fit(X, y)
w_est = model.coef_
w_est

array([ 0.04576465,  0.18853002, -0.00103749])